[colors.cursor]
cursor = "#36a9dc"

[colors.primary]
background = "#010712"
foreground = "#d4d8d5"

[font]
size = 14

[font.normal]
family = "Noto Sans Mono"
style = "Regular"

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t="

[window]
opacity = 0.9

[window.padding]
x = 2
y = 2
